# This rule is not used by the project operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the monarch.pytorch.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: monarch-operator
    app.kubernetes.io/managed-by: kustomize
  name: monarchmesh-editor-role
rules:
- apiGroups:
  - monarch.pytorch.org
  resources:
  - monarchmeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monarch.pytorch.org
  resources:
  - monarchmeshes/status
  verbs:
  - get
